- name: Common:- Import PostgreSQL key from a url
  rpm_key:
    state: present
    key: https://ftp.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG

- name: Common:- PostgreSQL 12 repo
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    state: present

- name: Common:- Install PostgreSQL 12 packages
  yum:
    name:
      - net-tools
      - nano
      - postgresql12
      - postgresql12-contrib
      - postgresql12-server
      - python3-psycopg2
    state: present

- name: "Enable PostgreSQL service on boot"
  systemd:
    name: postgresql-12.service
    state: started
    enabled: yes

- name: Create ssh direcotry for postgres user
  file:
    path: /var/lib/pgsql/.ssh
    state: directory
    owner: postgres
    group: postgres
    mode: 700

- name: Copy file to postgres user for password less ssh
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: postgres
    group: postgres
    mode: 700
    with_items:
      - "{ src: .bashrc , dest: /var/lib/pgsql }"
      - "{ src: .profile , dest: /var/lib/pgsql }"

- name: Copy file to postgres user for password less ssh
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: postgres
    group: postgres
    mode: 600
    with_items:
      - "{ src: 'id_ed25519_postgres' , dest: '/var/lib/pgsql/.ssh/' }"
      - "{ src: 'id_ed25519_postgres.pub' , dest: '/var/lib/pgsql/.ssh/' }"
      - "{ src: 'authorized_keys' , dest: '/var/lib/pgsql/.ssh/' }"
