---
- hosts: localhost
  become: true
  vars:
    create_containers: 4
    default_container_name: docker
    default_container_image: centos
    # default_container_command: yum install openssh-server && systemctl start ssh && sleep 1d
    default_container_command: sleep 1d

  tasks:

    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: started
        # env: 
        #   ENV: http_proxy "http://172.16.0.28:8080"
        #   ENV: https_proxy "http://172.16.0.28:8080"
        #   ENV: ftp_proxy "http://172.16.0.28:8080"
      with_sequence: count={{ create_containers }}