---

- name: Main play
  hosts: db_hosts, watcher
  become: true

  tasks:

  - name: Execute prequisites on all hosts
    import_tasks: base.yml


- name: DB Master Play
  hosts: dbmaster
  become: true

  tasks:

  - name: Setup PostgreSQL Master Server
    import_tasks: master.yml

  handlers:
    - name: Restart database
      systemd:
        state: restarted
        name: postgresql-12
      become: true

- name: DB Slave Play
  hosts: dbslaves
  become: true

  tasks:

  - name: Setup PostgreSQL Master Server
    import_tasks: slave.yml

  handlers:
    - name: Restart database
      systemd:
        state: restarted
        name: postgresql-12
      become: true

- name: PgBouncer Play
  hosts: watcher
  become: true

  tasks:

  - name: Setup PgBouncer Server
    import_tasks: pgbouncer.yml

  handlers:
    - name: Restart database
      systemd:
        state: restarted
        name: postgresql-12
      become: true