---

- name: Main play
  hosts: db_hosts, watcher
  become: true

  tasks:

  - name: Execute prequisites on all hosts
    import_tasks: base.yml


- name: DB Master Play
  hosts: dbmaster
  become: true

  tasks:

  - name: Setup PostgreSQL Master Server
    import_tasks: master.yml
